name: TransportingBarrels
version: 'Beta 1.2.0'
main: org.flipside.transportingbarrels.TransportingBarrels
api-version: '1.20'
authors: [Homka, Flipside Team]
description: plugin for retaining items when you breake barrel
