name: FlipSide-TransportingBarrels
version: '1.0-SNAPSHOT'
main: org.flipside.mc.flipsidetransportingbarrels.FlipSide_TransportingBarrels
api-version: 1.19
authors: [FlipSide Team]
description: github - https://github.com/JustHomka/FlipSide-TransportingBarrels
