name: FlipSide-TransportingBarrels
version: 1.0.1
main: org.flipside.mc.flipsidetransportingbarrels.Main
api-version: 1.14
authors: [FlipSide Team]
description: github - https://github.com/JustHomka/FlipSide-TransportingBarrels
