name: FlipSide-TransportingBarrels
version: 1.0.0
main: org.flipside.mc.flipsidetransportingbarrels.Main
api-version: 1.14-1.19
authors: [FlipSide Team]
description: github - https://github.com/JustHomka/FlipSide-TransportingBarrels
